In [1]:
import numpy as np 

# 1 DataTypes & Attributes

In [2]:
# Numpy's main datatypes is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

## 

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# 2. Creating array 

In [14]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int64')

In [16]:
ones = np.ones((2,3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 6, 0, 4, 4],
       [5, 1, 7, 5, 0],
       [3, 6, 1, 0, 6]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.32208585, 0.66897987, 0.29664286],
       [0.90778121, 0.90015542, 0.33347077],
       [0.93936063, 0.67879735, 0.56101511],
       [0.60204718, 0.8195413 , 0.32627924],
       [0.86872839, 0.70801017, 0.10486599]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.63701572, 0.70394728, 0.14785162],
       [0.63137315, 0.23254673, 0.57256134],
       [0.40123559, 0.13025146, 0.30650327],
       [0.72555671, 0.61925091, 0.68994388],
       [0.21041879, 0.72432817, 0.15069054]])

In [29]:
# pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [30]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [31]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

# 3. Viewing arrays and matrics 

In [32]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [33]:
a1

array([1, 2, 3])

In [34]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1[0]

1

In [37]:
a2.shape

(2, 3)

In [38]:
a2[0]

array([1. , 2. , 3.3])

In [39]:
a3.shape

(2, 3, 3)

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a2[1]

array([4. , 5. , 6.5])

In [42]:
a3.shape

(2, 3, 3)

In [43]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [44]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [45]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [46]:
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

# 4 Manipulating & comparing arrays

# ARITHMETIC

In [47]:
a1

array([1, 2, 3])

In [48]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [49]:
a1 + ones

array([2., 3., 4.])

In [50]:
a1 - ones

array([0., 1., 2.])

In [51]:
a1* ones

array([1., 2., 3.])

In [52]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [53]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [54]:
a2 /a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [55]:
# Floor division - removes the decimal 
a2// a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
# u can use  **2  or square 
a2** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [58]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [59]:
a1 + ones

array([2., 3., 4.])

In [60]:
np.add(a1, ones)

array([2., 3., 4.])

In [61]:
a1 % 2

array([1, 0, 1])

In [62]:
a1 /2

array([0.5, 1. , 1.5])

In [63]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [64]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [65]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# AGGREGATION 

# Aggregation = performing the same operation on a number of things

In [66]:
listy_list = [1,2,3]
type(listy_list)

list

In [67]:
sum(listy_list)

6

In [68]:
sum(a1)

6

In [69]:
np.sum(a1)

6

# Use python's method (sum()) on python datatypes and use NUmpy's methods on numpy arrays(np.sum())

In [70]:
# creating a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [71]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [72]:
%timeit sum(massive_array) # python's sum()
%timeit np.sum(massive_array) # numpy's np.sum

19.3 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
38.6 µs ± 1.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [73]:
17900/34

526.4705882352941

In [74]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [75]:
np.mean(a2)

3.6333333333333333

In [76]:
np.max(a2)

6.5

In [77]:
np.min(a2)

1.0

In [78]:
np.std(a2)

1.8226964152656422

In [79]:
# variance -  measure of the avg degaree to which each number is difference
# Higher variance = wider range of numbers 
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

# Standard deviation and variance are measures of 'spread' of data

The higher standard deviation and the higher variance of data, the more spread out the values are.

The lower standard daviation and lower variance, the less spread out the values are.

In [80]:
# Standard daviation = a measure of hoe spread out a group of numbers from the mean 
np.std(a2)

1.8226964152656422

In [81]:
# Variance  = measure of the avg dagree to which each number is diff to the mean 
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [82]:
# Standard daviation = squareroot of variance 
np.sqrt(np.var(a2))

1.8226964152656422

In [83]:
# Demo of std and Var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [84]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [85]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [86]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)

In [120]:
%matplotlib inline
import matplot.pyplot as plt
plt.hist(high_var_array)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [118]:
plt.hist(low_var_array)
plt.show()

NameError: name 'plt' is not defined

# Reshaping & transposing 

In [121]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [122]:
a2.shape

(2, 3)

In [123]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [124]:
a3.shape

(2, 3, 3)

In [125]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [165]:
a2.shape

(2, 3)

In [127]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [128]:
a3.shape

(2, 3, 3)

In [129]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [130]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [131]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [132]:
a2.shape

(2, 3)

In [133]:
# Transpose = switches the axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [134]:
a2.T.shape

(3, 2)

In [135]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [136]:
a3.shape

(2, 3, 3)

In [137]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [138]:
a3.T.shape

(3, 3, 2)

# DOT PRODUCT 

In [169]:
np.random.seed(0)

mat1 = np.random.randint(10, size= (5,3))
mat2 = np.random.randint(10, size= (5,3))


mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [170]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [171]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [172]:
# Elemants-wise multipulication (Hadmard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [173]:
# Dot product 
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [174]:
# Transpose mat1
mat1.T 

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [175]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [176]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [177]:
mat3.shape

(5, 5)

# Dot product example (nut butter sales)

In [185]:
np.random.seed(0)
# Numbers of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [187]:
# Create weekly_sales Dataframe
weekly_sales = pd.Dataframe(sales_amount,
                             index=["Mon","Tues","wed","Thurs","Fri"],
                             columns=["Almond butter","Peanut Butter","Cashew butter"])

weekly_sales
 

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [182]:
# create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [152]:
prices.shape

(3,)

In [190]:
# Create  butter_prices Dataframe 
butter_prices = pd.Dataframe(prices,
                            index=["Price"],
                            columns=["Alomond butter", "Peanut butter","Cashew butter"])


butter_prices

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [154]:
prices.shape

(3,)

In [155]:
sales_amounts.shape

(5, 3)

In [156]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [157]:
# Shape aren't aligned let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [2]:
# create daily_sales
butter_prices.shape, weekly_sales.shape

NameError: name 'butter_prices' is not defined

In [159]:
weekly_sales.T.shape

NameError: name 'weekly_sales' is not defined

In [193]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

NameError: name 'butter_prices' is not defined

In [194]:
weekly_sales.shape

NameError: name 'weekly_sales' is not defined

In [162]:
weekly_sales

NameError: name 'weekly_sales' is not defined

In [200]:
# Doesn't work, not the right shape 
weekly_sales["Total ($)"] = daily_sales.T
weeklY_sales

NameError: name 'daily_sales' is not defined

### comparison operators 

In [197]:
a1

array([1, 2, 3])

In [198]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [199]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [202]:
bool_array = a1 >= a2 
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [203]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [204]:
a1>5

array([False, False, False])

In [205]:
a1 < 5

array([ True,  True,  True])

In [207]:
a1 == a1

array([ True,  True,  True])

In [208]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

# 5. sorting array 

In [209]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [210]:
random_array.shape

(3, 5)

In [213]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [214]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [215]:
np.argsort(a1)

array([0, 1, 2])

In [216]:
np.argmin(a1)

0

In [217]:
np.argmax(a1)

2

In [219]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [220]:
np.argmax(random_array, axis= 1)

array([4, 1, 1])

## 6. Practical Example - Numpy in action

In [231]:
<img src = "numpy-images/panda.png"/>

SyntaxError: invalid syntax (<ipython-input-231-21696845e46f>, line 1)